import { mount, flushPromises, type VueWrapper } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { IDBFactory, IDBKeyRange } from 'fake-indexeddb'
import { webcrypto } from 'node:crypto'
import { TextEncoder } from 'node:util'
import MemoryEditor from '../src/components/MemoryEditor.vue'
import { createTravelServices } from '../src/services/travel-services'
import type { LocalRepository, TravelPlatform } from '../src/services/contracts'
import type { Draft, Photo, Visit } from '../src/domain/models'
import { importPhotos } from '../src/editor/photos'

vi.mock('../src/editor/photos', async importOriginal => ({ ...await importOriginal<typeof import('../src/editor/photos')>(), importPhotos: vi.fn() }))
const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='
const photo = (id = 'photo-one'): Photo => ({ id, name: `${id}.png`, url: png })
const visit = (id = 'visit-one'): Visit => ({ id, createdAt: 1, placeId: 'yulong', date: '2025-01-01', note: '山顶的风', photos: [], coverId: null })
const draft = (overrides: Partial<Draft> = {}): Draft => ({ id: 'draft-one', visitId: 'visit-one', createdAt: 1, placeId: 'yulong', date: '2025-01-01', note: '未写完的回忆', photos: [], coverId: null, updatedAt: 1, ...overrides })
const mounted: VueWrapper[] = [], repositories: LocalRepository[] = []
function harness() {
  const platform: TravelPlatform = { indexedDB: new IDBFactory(), IDBKeyRange, crypto: webcrypto as unknown as Crypto, Blob, TextEncoder,
    setTimeout: (callback, delay) => setTimeout(callback, delay), clearTimeout: handle => clearTimeout(handle as ReturnType<typeof setTimeout>) }
  const services = createTravelServices({ platform, dbName: 'editor-test' })
  repositories.push(services.repository)
  return services
}
async function open(h = harness(), props: { placeId?: string; provinceId?: string; visit?: Visit } = {}) {
  const wrapper = mount(MemoryEditor, { attachTo: document.body, props: { open: true, placeId: 'yulong', ...props, repository: h.repository, catalogue: h.catalogue } })
  mounted.push(wrapper)
  await vi.waitFor(() => expect(wrapper.find('#yn-editor-note').exists()).toBe(true))
  await flushPromises()
  return { wrapper, ...h }
}
const button = (wrapper: VueWrapper, text: string) => wrapper.findAll('button').find(item => item.text() === text)!
async function submit(wrapper: VueWrapper) { await wrapper.get('form').trigger('submit'); await flushPromises() }
beforeEach(() => {
  // jsdom does not implement native dialog top-layer/focus trapping. These
  // stubs exercise component state, not claim browser or phone modal parity.
  Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function(this: HTMLDialogElement) { this.setAttribute('open', '') } })
  Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value: function(this: HTMLDialogElement) { this.removeAttribute('open') } })
  vi.mocked(importPhotos).mockResolvedValue({ photos: [], errors: [] })
})
afterEach(async () => {
  mounted.splice(0).forEach(wrapper => wrapper.unmount())
  await Promise.all(repositories.splice(0).map(repository => repository.close()))
  document.body.innerHTML = ''; vi.restoreAllMocks()
})

describe('native Vue memory editor with real IndexedDB transactions', () => {
  it('opens a labelled dialog with note focus, rejects empty content, and saves note-only after commit', async () => {
    const { wrapper, repository } = await open()
    expect(wrapper.get('dialog').attributes('aria-labelledby')).toBe('yn-editor-title')
    expect(document.activeElement).toBe(wrapper.get('textarea').element)
    await submit(wrapper)
    expect(wrapper.text()).toContain('选一张照片或写一句手记')
    expect((await repository.load()).visits).toEqual([])
    await wrapper.get('textarea').setValue('  山脚的热豆浆  ')
    await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    const row = (await repository.load()).visits[0]!
    expect(row.note).toBe('山脚的热豆浆'); expect(row.photos).toEqual([])
    expect(await repository.loadDraft()).toBeNull()
    expect(wrapper.emitted('saved')?.[0]?.[1]).toEqual({ edited: false })
  })
  it('keeps successful photos when another file fails, supports cover choice/removal, and saves photo-only', async () => {
    const { wrapper, repository } = await open()
    vi.mocked(importPhotos).mockResolvedValueOnce({ photos: [photo(), photo('photo-two')], errors: [{ name: 'broken.jpg', message: '照片损坏' }] })
    const input = wrapper.get<HTMLInputElement>('#yn-editor-photos')
    Object.defineProperty(input.element, 'files', { configurable: true, value: [new File(['abc'], 'photo.jpg')] })
    await input.trigger('change'); await flushPromises()
    expect(wrapper.findAll('.yn-draft-photo')).toHaveLength(2)
    expect(wrapper.text()).toContain('broken.jpg：照片损坏')
    await wrapper.get('[aria-label="将第 2 张设为封面"]').trigger('click')
    expect(wrapper.get('[aria-label="第 2 张是封面"]').attributes('aria-pressed')).toBe('true')
    await wrapper.get('[aria-label="移除第 1 张照片"]').trigger('click')
    await submit(wrapper); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    const row = (await repository.load()).visits[0]!
    expect(row.photos.map(p => p.id)).toEqual(['photo-two']); expect(row.coverId).toBe('photo-two'); expect(row.note).toBe('')
  })
  it('enforces a valid past date and 2000-character note before committing', async () => {
    const { wrapper, repository } = await open()
    await wrapper.get('textarea').setValue('x'.repeat(2001)); await submit(wrapper)
    expect(wrapper.text()).toContain('手记最多 2000 字')
    await wrapper.get('textarea').setValue('日期检查'); await wrapper.get('#yn-editor-date').setValue('2099-01-01'); await submit(wrapper)
    expect(wrapper.text()).toContain('不能晚于今天'); expect((await repository.load()).visits).toEqual([])
  })
  it('keeps a failed save open, does not emit success, and retries the same identity', async () => {
    const { wrapper, repository } = await open()
    const add = vi.spyOn(repository, 'addVisit').mockRejectedValueOnce(Object.assign(new Error('空间不足'), { friendlyMessage: '存储空间不足' }))
    await wrapper.get('textarea').setValue('保留这句话'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('存储空间不足'))
    expect(wrapper.emitted('saved')).toBeUndefined(); expect(wrapper.get('dialog').attributes('open')).toBeDefined()
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('保留这句话')
    const firstId = add.mock.calls[0]![0].id
    await submit(wrapper); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect(add.mock.calls[1]![0].id).toBe(firstId); expect((await repository.load()).visits).toHaveLength(1)
  })
  it('updates with original visit CAS and preserves a concurrent edit on stale failure', async () => {
    const h = harness(), original = visit()
    await h.repository.addVisit(original)
    const { wrapper } = await open(h, { visit: original })
    const update = vi.spyOn(h.repository, 'updateVisit')
    await h.repository.updateVisit({ ...original, note: '另一页更新' }, { expectedVisit: original })
    await wrapper.get('textarea').setValue('本页更新'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('当前草稿仍保留'))
    expect(update.mock.calls.at(-1)?.[1]).toEqual({ expectedVisit: original })
    expect((await h.repository.load()).visits[0]?.note).toBe('另一页更新'); expect(wrapper.emitted('saved')).toBeUndefined()
    expect(wrapper.text()).toContain('另存为新回忆')
  })
  it('saves an edit and preserves custom metadata; renaming gets a separate custom place identity', async () => {
    const h = harness(), custom = { id: 'custom-one', name: '自己的雪山位置', regionId: 'lijiang', coordinates: [100.19, 27.09] as [number, number] }
    const original: Visit = { ...visit(), placeId: custom.id, customPlace: custom }
    await h.repository.addVisit(original); h.catalogue.replaceCustomPlaces([original])
    const { wrapper } = await open(h, { visit: original })
    await wrapper.get('#yn-editor-custom-name').setValue('雪山下的茶馆'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    const saved = (await h.repository.load()).visits[0]!
    expect(saved.id).toBe(original.id); expect(saved.placeId).not.toBe(custom.id); expect(saved.customPlace?.coordinates).toEqual(custom.coordinates)
    expect(wrapper.emitted('saved')?.[0]?.[1]).toEqual({ edited: true }); expect(custom.name).toBe('自己的雪山位置')
  })
  it('autosaves using a version token and a remount resumes without replacing it with the requested place', async () => {
    const h = harness(), { wrapper } = await open(h)
    await wrapper.get('textarea').setValue('自动保存的手记')
    await vi.waitFor(async () => expect((await h.repository.loadDraft())?.note).toBe('自动保存的手记'), { timeout: 1500 })
    const first = await h.repository.loadDraft()
    expect(first?.version).toEqual(expect.any(String))
    wrapper.unmount(); mounted.splice(mounted.indexOf(wrapper), 1)
    const reopened = await open(h, { placeId: 'dali-oldtown' })
    expect((reopened.wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('自动保存的手记')
    expect(reopened.wrapper.text()).toContain('正在继续未完成的草稿')
    await reopened.wrapper.get('textarea').setValue('继续写完'); await submit(reopened.wrapper)
    await vi.waitFor(() => expect(reopened.wrapper.emitted('saved')).toHaveLength(1))
    expect((await h.repository.load()).visits[0]?.placeId).toBe('yulong')
  })
  it('Escape preserves dirty content and offers explicit durable-close; failure stays open', async () => {
    const { wrapper, repository } = await open()
    await wrapper.get('textarea').setValue('尚未存好')
    await wrapper.get('dialog').trigger('cancel')
    expect(wrapper.text()).toContain('本页还有尚未保存的更改')
    expect(wrapper.emitted('close')).toBeUndefined(); expect(document.activeElement).toBe(button(wrapper, '继续编辑').element)
    vi.spyOn(repository, 'saveDraft').mockRejectedValueOnce(new Error('草稿写入失败'))
    await button(wrapper, '保存草稿并关闭').trigger('click'); await flushPromises()
    expect(wrapper.text()).toContain('草稿写入失败'); expect(wrapper.emitted('close')).toBeUndefined()
    await button(wrapper, '保存草稿并关闭').trigger('click'); await vi.waitFor(() => expect(wrapper.emitted('close')).toHaveLength(1))
    expect((await repository.loadDraft())?.note).toBe('尚未存好')
  })
  it('asks before duplicate place/date creation and commits only after the explicit confirmation', async () => {
    const h = harness(); await h.repository.addVisit(visit('older'))
    const { wrapper } = await open(h)
    const fullLoad = vi.spyOn(h.repository, 'load').mockRejectedValue(new Error('whole-library photos must not be read for duplicate checks'))
    const indexLoad = vi.spyOn(h.repository, 'loadIndex'), singleRead = vi.spyOn(h.repository, 'readVisit')
    await wrapper.get('#yn-editor-date').setValue('2025-01-01'); await wrapper.get('textarea').setValue('当天第二段'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('当天已有回忆'))
    expect((await h.repository.loadIndex()).visits).toHaveLength(1)
    await button(wrapper, '仍然添加回忆').trigger('click'); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect((await h.repository.loadIndex()).visits).toHaveLength(2)
    expect(indexLoad).toHaveBeenCalled(); expect(singleRead).not.toHaveBeenCalled(); expect(fullLoad).not.toHaveBeenCalled()
  })
  it('warns separately if draft cleanup fails after commit, and a retry does not duplicate the visit', async () => {
    const { wrapper, repository } = await open()
    vi.spyOn(repository, 'clearDraft').mockRejectedValueOnce(new Error('清理失败'))
    await wrapper.get('textarea').setValue('已经保存'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect(wrapper.emitted('saved')?.[0]?.[1]).toMatchObject({ draftWarning: expect.stringContaining('回忆已保存') })
    expect((await repository.load()).visits).toHaveLength(1)
    await wrapper.setProps({ open: false }); await wrapper.setProps({ open: true }); await flushPromises(); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(2))
    expect((await repository.load()).visits).toHaveLength(1); expect(await repository.loadDraft()).toBeNull()
  })
  it('does not overwrite a newer remote draft; confirmed reload replaces local content only after a valid read', async () => {
    const h = harness(), saved = await h.repository.saveDraft(draft(), { expectedVersion: null })
    const { wrapper } = await open(h)
    await h.repository.saveDraft({ ...saved, note: '另一页的草稿' }, { expectedVersion: saved.version })
    await wrapper.get('textarea').setValue('本页保留'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.find('[aria-label="草稿冲突处理"]').exists()).toBe(true))
    expect((await h.repository.loadDraft())?.note).toBe('另一页的草稿')
    await button(wrapper, '载入另一份草稿').trigger('click')
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('本页保留')
    await button(wrapper, '确认载入另一份草稿').trigger('click')
    await vi.waitFor(() => expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('另一页的草稿'))
  })
  it('a cleared remote draft requires explicit fork and creates fresh draft/visit identities, not a saved memory', async () => {
    const h = harness(), saved = await h.repository.saveDraft(draft(), { expectedVersion: null })
    const { wrapper } = await open(h)
    await h.repository.clearDraft(saved.id, { expectedVersion: saved.version })
    await wrapper.get('textarea').setValue('空位后的本页内容'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('检查草稿状态'))
    await button(wrapper, '检查草稿状态').trigger('click'); await vi.waitFor(() => expect(wrapper.text()).toContain('确认另存本页草稿'))
    expect(await h.repository.loadDraft()).toBeNull()
    await button(wrapper, '确认另存本页草稿').trigger('click')
    await vi.waitFor(async () => expect((await h.repository.loadDraft())?.note).toBe('空位后的本页内容'))
    const fork = await h.repository.loadDraft()
    expect(fork?.id).not.toBe(saved.id); expect(fork?.visitId).not.toBe(saved.visitId)
    expect(fork?.originalVisit).toBeUndefined(); expect((await h.repository.load()).visits).toEqual([])
  })
  it('requires two-step discard and preserves saved visits', async () => {
    const h = harness(); await h.repository.addVisit(visit('keep')); await h.repository.saveDraft(draft(), { expectedVersion: null })
    const { wrapper } = await open(h)
    await button(wrapper, '放弃草稿').trigger('click'); expect(await h.repository.loadDraft()).not.toBeNull()
    await button(wrapper, '确认放弃这份草稿').trigger('click'); await vi.waitFor(() => expect(wrapper.emitted('close')).toHaveLength(1))
    expect(await h.repository.loadDraft()).toBeNull(); expect((await h.repository.load()).visits.map(v => v.id)).toEqual(['keep'])
  })
  it('creates a custom location only after receiving validated map coordinates and allows cancelling map pick', async () => {
    const { wrapper, repository } = await open()
    await wrapper.get('#yn-editor-place').setValue('__custom')
    await wrapper.get('#yn-editor-custom-name').setValue('小茶馆'); await wrapper.get('#yn-editor-custom-region').setValue('lijiang')
    await button(wrapper, '到地图选位置').trigger('click'); await vi.waitFor(() => expect(wrapper.emitted('pick-location')).toHaveLength(1))
    const exposed = wrapper.vm as unknown as { acceptLocation(point: [number, number]): Promise<boolean>; cancelLocationPick(): Promise<void> }
    expect(await exposed.acceptLocation([0, 0])).toBe(false)
    expect(wrapper.emitted('location-error')?.[0]?.[0]).toEqual(expect.any(String))
    expect((await repository.loadDraft())?.customPlace?.coordinates).toBeNull()
    await exposed.cancelLocationPick(); expect(wrapper.get('dialog').attributes('open')).toBeDefined()
    await button(wrapper, '到地图选位置').trigger('click'); await vi.waitFor(() => expect(wrapper.emitted('pick-location')).toHaveLength(2))
    expect(await exposed.acceptLocation([100.19, 27.09])).toBe(true)
    await wrapper.get('textarea').setValue('当地喝茶'); await submit(wrapper); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect((await repository.load()).visits[0]?.customPlace?.coordinates).toEqual([100.19, 27.09])
  })
  it('stores and resumes a Sichuan custom draft by regionId, then saves it without introducing a provinceId field', async () => {
    const h = harness(), { wrapper } = await open(h)
    await wrapper.get('#yn-editor-place').setValue('__custom')
    expect(wrapper.get('#yn-editor-custom-province').findAll('option')).toHaveLength(34)
    await wrapper.get('#yn-editor-custom-province').setValue('cn-51')
    expect(wrapper.find('#yn-editor-custom-region').exists()).toBe(false)
    await wrapper.get('#yn-editor-custom-name').setValue('成都的小茶馆')
    await button(wrapper, '到地图选位置').trigger('click')
    await vi.waitFor(() => expect(wrapper.emitted('pick-location')).toHaveLength(1))
    expect(wrapper.emitted('pick-location')?.[0]?.[0]).toMatchObject({ regionId: 'cn-51' })
    const exposed = wrapper.vm as unknown as { acceptLocation(point: [number, number]): Promise<boolean> }
    expect(await exposed.acceptLocation([104.0665, 30.5728])).toBe(true)
    await wrapper.get('textarea').setValue('雨天在成都喝茶')
    await wrapper.get('dialog').trigger('cancel')
    await button(wrapper, '保存草稿并关闭').trigger('click')
    await vi.waitFor(() => expect(wrapper.emitted('close')).toHaveLength(1))
    const savedDraft = await h.repository.loadDraft()
    expect(savedDraft?.customPlace).toMatchObject({ regionId: 'cn-51', coordinates: [104.0665, 30.5728] })
    expect(savedDraft).not.toHaveProperty('provinceId'); expect(savedDraft?.customPlace).not.toHaveProperty('provinceId')
    wrapper.unmount(); mounted.splice(mounted.indexOf(wrapper), 1)
    const reopened = await open(h, { placeId: 'yulong' })
    expect((reopened.wrapper.get('#yn-editor-custom-province').element as HTMLSelectElement).value).toBe('cn-51')
    expect((reopened.wrapper.get('#yn-editor-province').element as HTMLSelectElement).value).toBe('cn-51')
    expect(reopened.wrapper.find('#yn-editor-custom-region').exists()).toBe(false)
    await submit(reopened.wrapper)
    await vi.waitFor(() => expect(reopened.wrapper.emitted('saved')).toHaveLength(1))
    expect((await h.repository.load()).visits[0]?.customPlace).toMatchObject({ regionId: 'cn-51', coordinates: [104.0665, 30.5728] })
  })
  it('opens a new custom place directly in the requested outside province and can pick without reselecting it', async () => {
    const { wrapper } = await open(harness(), { placeId: '__custom', provinceId: 'cn-11' })
    expect((wrapper.get('#yn-editor-custom-province').element as HTMLSelectElement).value).toBe('cn-11')
    expect(wrapper.find('#yn-editor-custom-region').exists()).toBe(false)
    await wrapper.get('#yn-editor-custom-name').setValue('北京的小胡同')
    await button(wrapper, '到地图选位置').trigger('click')
    await vi.waitFor(() => expect(wrapper.emitted('pick-location')).toHaveLength(1))
    expect(wrapper.emitted('pick-location')?.[0]?.[0]).toMatchObject({ regionId: 'cn-11', coordinates: null })
  })
  it('derives the province of an existing Yunnan record and clears coordinates when the custom province changes', async () => {
    const h = harness(), custom = { id: 'custom-old', name: '雪山茶馆', regionId: 'lijiang', coordinates: [100.19, 27.09] as [number, number] }
    const original: Visit = { ...visit(), placeId: custom.id, customPlace: custom }
    await h.repository.addVisit(original); h.catalogue.replaceCustomPlaces([original])
    const { wrapper } = await open(h, { visit: original })
    expect((wrapper.get('#yn-editor-custom-province').element as HTMLSelectElement).value).toBe('yunnan')
    expect((wrapper.get('#yn-editor-custom-region').element as HTMLSelectElement).value).toBe('lijiang')
    await wrapper.get('#yn-editor-custom-province').setValue('cn-51')
    expect(wrapper.get('.yn-custom-position').text()).toBe('尚未选择地图位置')
    await vi.waitFor(async () => expect((await h.repository.loadDraft())?.customPlace).toMatchObject({ regionId: 'cn-51', coordinates: null }), { timeout: 1500 })
    await wrapper.get('#yn-editor-custom-province').setValue('yunnan')
    expect((wrapper.get('#yn-editor-custom-region').element as HTMLSelectElement).value).toBe('')
    expect((await h.repository.load()).visits[0]?.customPlace).toEqual(custom)
  })
  it('keeps the selected public place available while browsing another province in the editor', async () => {
    const { wrapper } = await open()
    await wrapper.get('#yn-editor-province').setValue('cn-51')
    const selected = wrapper.get<HTMLSelectElement>('#yn-editor-place')
    expect(selected.element.value).toBe('yulong')
    expect(selected.find('option[value="yulong"]').exists()).toBe(true)
    expect(selected.find('option[value="dali-oldtown"]').exists()).toBe(false)
  })
  it('does not emit saved or allow closing while the actual visit write is still pending', async () => {
    const { wrapper, repository } = await open()
    const add = repository.addVisit.bind(repository)
    let release!: () => void
    const barrier = new Promise<void>(resolve => { release = resolve })
    const pendingAdd = vi.spyOn(repository, 'addVisit').mockImplementation(async row => { await barrier; return add(row) })
    await wrapper.get('textarea').setValue('等事务提交'); await submit(wrapper)
    await vi.waitFor(() => expect(pendingAdd).toHaveBeenCalledTimes(1))
    expect(wrapper.emitted('saved')).toBeUndefined()
    expect((await repository.load()).visits).toEqual([])
    expect(wrapper.get('[aria-label="关闭回忆编辑器"]').attributes('disabled')).toBeDefined()
    await wrapper.get('dialog').trigger('cancel'); expect(wrapper.emitted('close')).toBeUndefined()
    release(); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect((await repository.load()).visits[0]?.note).toBe('等事务提交')
  })
  it('rejects a fork if another page claims the empty slot after checking, retaining both pages content', async () => {
    const h = harness(), saved = await h.repository.saveDraft(draft(), { expectedVersion: null })
    const { wrapper } = await open(h)
    await h.repository.clearDraft(saved.id, { expectedVersion: saved.version })
    await wrapper.get('textarea').setValue('准备另存的本页内容'); await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('检查草稿状态'))
    await button(wrapper, '检查草稿状态').trigger('click'); await vi.waitFor(() => expect(wrapper.text()).toContain('确认另存本页草稿'))
    await h.repository.saveDraft(draft({ id: 'draft-racer', visitId: 'visit-racer', note: '另一页刚占用' }), { expectedVersion: null })
    await button(wrapper, '确认另存本页草稿').trigger('click')
    await vi.waitFor(() => expect(wrapper.get('[role="alert"]').text()).toContain('草稿'))
    expect((await h.repository.loadDraft())?.note).toBe('另一页刚占用')
    expect((wrapper.get('textarea').element as HTMLTextAreaElement).value).toBe('准备另存的本页内容')
    expect((await h.repository.load()).visits).toEqual([])
  })
  it('recognizes a previously committed draft without asking to add another same-day memory', async () => {
    const h = harness(), already = { ...visit(), photos: [photo('one'), photo('two')], coverId: 'two' }
    await h.repository.addVisit(already); await h.repository.addVisit({ ...visit('same-day'), note: '另一段' })
    await h.repository.saveDraft(draft({ note: already.note, photos: already.photos, coverId: already.coverId }), { expectedVersion: null })
    const { wrapper } = await open(h), add = vi.spyOn(h.repository, 'addVisit')
    const revision = (await h.repository.loadIndex()).revision
    const fullLoad = vi.spyOn(h.repository, 'load').mockRejectedValue(new Error('whole-library photo read forbidden'))
    const singleRead = vi.spyOn(h.repository, 'readVisit')
    await submit(wrapper); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect(add).not.toHaveBeenCalled(); expect((await h.repository.loadIndex()).visits).toHaveLength(2)
    expect(singleRead).toHaveBeenCalledExactlyOnceWith(already.id, { expectedRevision: revision })
    expect(fullLoad).not.toHaveBeenCalled()
    expect(await h.repository.loadDraft()).toBeNull(); expect(wrapper.find('[aria-label="同日回忆确认"]').exists()).toBe(false)
  })
  it('compares the complete same-id photo content rather than mistaking a summary for an identical saved visit', async () => {
    const h = harness(), stored = { ...visit(), photos: [photo('one'), photo('two')], coverId: 'two' }
    await h.repository.addVisit(stored)
    await h.repository.saveDraft(draft({ note: stored.note, photos: [photo('two'), photo('one')], coverId: 'two' }), { expectedVersion: null })
    const { wrapper } = await open(h)
    const fullLoad = vi.spyOn(h.repository, 'load').mockRejectedValue(new Error('whole-library photo read forbidden'))
    const singleRead = vi.spyOn(h.repository, 'readVisit'), add = vi.spyOn(h.repository, 'addVisit'), update = vi.spyOn(h.repository, 'updateVisit')
    await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('另一页已经保存了这份草稿对应的回忆'))
    expect(singleRead).toHaveBeenCalledTimes(1); expect(singleRead.mock.calls[0]?.[0]).toBe(stored.id)
    expect(wrapper.emitted('saved')).toBeUndefined(); expect(add).not.toHaveBeenCalled(); expect(update).not.toHaveBeenCalled()
    expect(fullLoad).not.toHaveBeenCalled()
    expect((await h.repository.readVisit(stored.id))?.photos.map(item => item.id)).toEqual(['one', 'two'])
    expect((await h.repository.loadDraft())?.photos.map(item => item.id)).toEqual(['two', 'one'])
  })
  it('retains the draft if the index revision is stale before the single-record comparison, then retries safely', async () => {
    const h = harness(), stored = visit()
    await h.repository.addVisit(stored)
    await h.repository.saveDraft(draft({ note: stored.note }), { expectedVersion: null })
    const { wrapper } = await open(h)
    const fullLoad = vi.spyOn(h.repository, 'load').mockRejectedValue(new Error('whole-library photo read forbidden'))
    const singleRead = vi.spyOn(h.repository, 'readVisit').mockRejectedValueOnce(Object.assign(new Error('资料已经变化，请重新读取。'), { code: 'stale' }))
    const add = vi.spyOn(h.repository, 'addVisit'), update = vi.spyOn(h.repository, 'updateVisit'), clear = vi.spyOn(h.repository, 'clearDraft')
    await submit(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('资料已经变化'))
    expect(wrapper.text()).toContain('当前草稿仍保留')
    expect(wrapper.emitted('saved')).toBeUndefined(); expect(await h.repository.loadDraft()).not.toBeNull()
    expect(add).not.toHaveBeenCalled(); expect(update).not.toHaveBeenCalled(); expect(clear).not.toHaveBeenCalled()
    await submit(wrapper); await vi.waitFor(() => expect(wrapper.emitted('saved')).toHaveLength(1))
    expect(singleRead).toHaveBeenCalledTimes(2)
    expect((await h.repository.loadIndex()).visits).toHaveLength(1); expect(await h.repository.loadDraft()).toBeNull()
    expect(fullLoad).not.toHaveBeenCalled(); expect(add).not.toHaveBeenCalled(); expect(update).not.toHaveBeenCalled()
  })
  it('does not create a fresh draft after a failed initial read and requires explicit malformed-draft removal', async () => {
    const h = harness(), saved = await h.repository.saveDraft(draft(), { expectedVersion: null })
    const read = vi.spyOn(h.repository, 'loadDraft').mockRejectedValueOnce(Object.assign(new Error('无法安全读取草稿'), { code: 'invalid-draft', recoverableDraft: { id: saved.id, expectedVersion: saved.version } }))
    const wrapper = mount(MemoryEditor, { attachTo: document.body, props: { open: true, repository: h.repository, catalogue: h.catalogue } }); mounted.push(wrapper)
    await vi.waitFor(() => expect(wrapper.text()).toContain('移除无法读取的草稿'))
    expect(wrapper.find('textarea').exists()).toBe(false)
    expect(read).toHaveBeenCalledTimes(1)
    await button(wrapper, '移除无法读取的草稿').trigger('click'); expect((await h.repository.loadDraft())?.id).toBe(saved.id)
    await button(wrapper, '确认移除无法读取的草稿（不影响已存回忆）').trigger('click')
    await vi.waitFor(() => expect(wrapper.find('textarea').exists()).toBe(true))
    expect(await h.repository.loadDraft()).toBeNull(); expect((await h.repository.load()).visits).toEqual([])
  })
})
